### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by HalfKnightDrummer** [McTsts/inv-manipulation#1]
I want to know if i can modify the function files that it works for multiple players, or if i can store multiple inventories, because if 2 players store their inventories and do the inv:loaad function everyone will get the last saved inventory (obviously)

**Comment by McTsts** [comment]
You can run save, then copy from 'inv:main inv.all' to somewhere else, then before you load you copy from your own thing to 'inv:main inv.all' again
